language: node_js

node_js: "node"

install: npm install

script: npm test

after_script: npm install coveralls && npm run coveralls
services:
  - postgresql

before_script:
  - npm install -g sequelize-cli
  - npm install strip-ansi --save
  - psql -c 'create database barefoot_nomad_test;' -U postgres

env:
  global: 
  - GOOGLE_CLIENT_ID=187094110790-i79hlolkav2se8e4s135dvsdcc78m20b.apps.googleusercontent.com
  - GOOGLE_CLIENT_SECRET=ZYjqoQT9Kg2HA9t52xl1M1vM
  - GOOGLE_ACCESS_TOKEN="ya29.Il-bB2DfpqJXKCJXsZuU6w1iwdTbypqHpV2rf7bs1RT1N7GLwe0hmLEMhlRubgVrt0gnP9hbKxElS1VYe-XKkEp-jskxuRk-XEABT3NSGXFIqcalO9ydOfEoXWStEIC6Ww"

  - FACEBOOK_CLIENT_ID=2619143904814570
  - FACEBOOK_CLIENT_SECRET=bc033f1f3a0608900efcf0fce19b5949
  - FACEBOOK_ACCESS_TOKEN=EAAlOGPYP5eoBAPXBhQNGkD9sGhmzrK9vI3WoOBONEdLYWTQqj6tYXaZCypWiyjhEid6JqOwK2cZCSy1vAZCC1QcbZBnHGacwMgxF0QlU1yrToEJw3v4bCsZBUENZBUWAHsgIvi9KdSsX5FnQk4fO3qU0ZAM43FnH6MiDZA4JMT3BMQZDZD
