language: node_js

node_js: "stable"

install: npm install

script: npm test

after_script: npm install coveralls && npm run coveralls
services:
  - postgresql

before_script:
  - npm install -g sequelize-cli
  - psql -c 'create database barefoot_nomad_test;' -U postgres
