version: '3.3'
services:
  db: 
    image: postgres
    environment: 
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_DB:${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      
  api:
    image: barefoot-nomad-api
    depends_on:
      - db
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
